<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Admin/Admin.Master"
    Inherits="NHDNUG.Mvc.Admin.Admin_Sponsors" CodeBehind="Sponsors.aspx.cs" %>

<%@ Register Assembly="System.Web.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
    Namespace="System.Web.UI.WebControls" TagPrefix="asp" %>
<asp:Content ContentPlaceHolderID="pageBody" runat="server">
    <asp:EntityDataSource ID="SponsorsListEntityDataSource" runat="server" ConnectionString="name=NhdnugEntities"
        DefaultContainerName="NhdnugEntities" EnableDelete="True" EnableInsert="True"
        EnableUpdate="True" EntitySetName="SponsorSet" OrderBy="it.Name">
    </asp:EntityDataSource>
    <br />
    <telerik:RadGrid ID="RadGrid1" runat="server" AllowAutomaticDeletes="True" AllowAutomaticInserts="True"
        AllowAutomaticUpdates="True" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteColumn="True"
        AutoGenerateEditColumn="True" DataSourceID="SponsorsListEntityDataSource" GridLines="None">
        <MasterTableView AutoGenerateColumns="False" CellSpacing="-1" DataKeyNames="SponsorID"
            DataSourceID="SponsorsListEntityDataSource" CommandItemDisplay="Top">
            <Columns>
                <telerik:GridBoundColumn DataField="SponsorID" DataType="System.Int32" HeaderText="SponsorID"
                    ReadOnly="True" SortExpression="SponsorID" 
                    UniqueName="SponsorID" Visible="false">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="Name" HeaderText="Name" SortExpression="Name"
                    UniqueName="Name">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="URL" HeaderText="URL" SortExpression="URL" UniqueName="URL">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="LogoFileName" HeaderText="LogoFileName" SortExpression="LogoFileName"
                    UniqueName="LogoFileName">
                </telerik:GridBoundColumn>
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
</asp:Content>
